Adds a new article: "Five Git Tricks To Make Crafting Software Easier"
incubyte/incubyte.github.io pull request #65
Opened 2022-06-13 20:54 UTC by 2KAbhishek

- Add first draft
- Add image

2022-06-15 07:04 UTC, ArohiParikh commented on content/blog/five-git-tricks.md
> +## 1. Quickly set up git ssh credentials with GitHub CLI
git ssh --> Check capitalisation

2022-06-15 07:08 UTC, ArohiParikh commented on content/blog/five-git-tricks.md
> +Now that we are all set up with git credentials and have cloned the repo, it's time to create a new and start working on that new feature.
it's time to create a new ________ ??

2022-06-15 07:59 UTC, sapanparikh18 commented on content/blog/five-git-tricks.md
> +Now that we are all set up with git credentials and have cloned the repo, it's time to create a new and start working on that new feature.
Branch?

2022-06-15 08:00 UTC, sapanparikh18 commented on content/blog/five-git-tricks.md
> +Now that we are all set up with git credentials and have cloned the repo, it's time to create a new and start working on that new feature.
@2KAbhishek

2022-06-15 08:00 UTC, sapanparikh18 requested changes
One small change @ArohiParikh  has suggested, please fix it

2022-06-15 08:06 UTC, ArohiParikh commented on content/blog/five-git-tricks.md
> +
Would be nice to add a list of the 5 tricks upfront and then dive deeper into each

2022-06-15 12:31 UTC, 2KAbhishek commented
Resolved comments

2022-06-16 10:54 UTC, ArohiParikh approved these changes

2022-06-16 10:54 UTC, merged