Rails RESTful api outside in tdd
incubyte/incubyte.github.io pull request #79
Opened 2022-07-07 05:11 UTC by nitinrajkumar451

The following is a blog about a , conceited programmer's journey in developing a simple TODO RESTful API using Ruby on Rails. How the quest for solutions to the challenges he faced at every step drifted him towards employing outside in Test driven development. Written in first person subjective.

2022-07-11 05:29 UTC, 2KAbhishek commented
Just made a bunch of fixes to the content.

I'd suggest running it through grammarly once.
After that open up the preview on your local with `hugo serve`, some sections look too dense and wordy, trim it or add some separation to improve readability.

2022-07-11 05:33 UTC, 2KAbhishek requested changes
Please check comment above

2022-08-01 09:59 UTC, 2KAbhishek approved these changes

2022-08-19 18:34 UTC, yoursPerilously requested changes

2022-08-19 18:34 UTC, yoursPerilously commented on content/blog/rails-restapi-outside-in-tdd.md
> +Now that the runner spec is fixed, so has run the request spec to check if it has been fixed too?
Need more clarity.

2022-08-19 18:34 UTC, yoursPerilously commented on content/blog/rails-restapi-outside-in-tdd.md
> +### It is always quite a sight to see all green
### All Green - quite a wonderful sight!

2022-08-19 18:34 UTC, yoursPerilously commented on content/blog/rails-restapi-outside-in-tdd.md
> +I was so immersed into conversing with rspec to develop this code, I felt like I was a part of a play, playing a character and that the play is being observed, and I am responding only when there is
I was so immersed in conversing with rspec while developing this application that I kind of got distanced from reality. I felt like I’d embodied this character in a play that was being watched and I was to only act out my lines on cue lest I’d mislead the audience. Rspec called the shots here!

2022-08-19 18:34 UTC, yoursPerilously commented on content/blog/rails-restapi-outside-in-tdd.md
> +In this manner I finished the assignment and gave it to the client.
And there you have it, folks! I finally ended up finishing the assignment and got it ready to be handed over to the client!

2022-08-19 18:34 UTC, yoursPerilously commented on content/blog/rails-restapi-outside-in-tdd.md
> +I had two days to go for a visit around the place.
With a couple of days left of my stay, I started out on my journey exploring the unknown!

2022-08-19 18:34 UTC, yoursPerilously commented on content/blog/rails-restapi-outside-in-tdd.md
> +As I was watching a tomb my instinctive thoughts about the plausible errors in my work started to take over me but with the fact that there never existed any piece of code before going through a test
At one such moment, I was looking at a tomb over at the distance when dreadful thoughts started to creep back in! Thoughts of possible errors in the app! But, I put all of that to rest as I’d let the tests do their magic now. 



------did I change the meaning of the block?

2022-08-19 18:34 UTC, yoursPerilously commented on content/blog/rails-restapi-outside-in-tdd.md
> +The sightseeing was pleasant with nothing in the back of my mind.
Now, with my mind at ease and feeling a sense of achievement, the sights all around seemed a bit more pleasant!

2022-10-10 06:44 UTC, 2KAbhishek approved these changes

2022-10-10 06:44 UTC, merged