Create bdd-case-study
incubyte/incubyte.github.io pull request #81
Opened 2022-07-15 10:48 UTC by ArohiParikh

2022-08-08 13:53 UTC, rushaliparikh requested changes
When the blog gets into the details of the BDD approach, I think we can do a better job at explaining the process and the benefits. I haven't added line by line suggestions for the last three statements, but it needs work to do justice to the case study.

2022-08-08 13:53 UTC, rushaliparikh commented on content/blog/bdd-case-study.md
> +## Implementing Behavior Driven Deployment methodologies to get better Software out the door - a case study
Development, not Deployment. Also, check capitalization - don't think Software should be capitalized

2022-08-08 13:53 UTC, rushaliparikh commented on content/blog/bdd-case-study.md
> +Over the years, the software development process has seen a massive change of pace. Through ideation, design, development, testing and implementation all the processes involve multiple teams. These g
```suggestion
Over the years, the software development process has seen a massive change of pace. Through ideation, design, development, testing, and implementation, all processes involve multiple skills, which have traditionally been served through multiple teams. These groups have varied responsibilities and need to work in a cohesive manner to achieve the end goal.
```

2022-08-08 13:53 UTC, rushaliparikh commented on content/blog/bdd-case-study.md
> +## Bogged down by Waterfall:
```suggestion
## Bogged down by Waterfall
```

2022-08-08 13:53 UTC, rushaliparikh commented on content/blog/bdd-case-study.md
> +## Focus on behavior and not tools:
```suggestion
## Focus on behavior and not tools
```

2022-08-08 13:53 UTC, rushaliparikh commented on content/blog/bdd-case-study.md
> +## TDD helps circumvent these issues by:
```suggestion
**Practices like TDD and BDD help circumvent these issues by:**
```

2022-08-08 13:53 UTC, rushaliparikh commented on content/blog/bdd-case-study.md
> +Using the “shift testing/QA to the left” approach, BDD ensures the essence of what the software is supposed to do, is completely and evenly spread across all vital stakeholders, including QAs and PAs
```suggestion
Enabling a "fail fast" approach, BDD ensures that the essence of what the software is supposed to do is created in an executable format, bringing in not just automation, but also full clarity around expected behaviour from the get-go.
```

2022-08-27 07:34 UTC, sapanparikh18 requested changes
This blog does not really look like a case study but rather a tutorial on BDD. Needs to be re-written

2022-08-27 07:34 UTC, sapanparikh18 commented on content/blog/bdd-case-study.md
> +## Focus on behavior and not tools
I think it should be not THE tool

2022-11-21 08:02 UTC, 2KAbhishek commented
Duplicate of #95

2022-11-21 08:02 UTC, closed without merging